export const REQUEST_LIST_ALL ='REQUEST_LIST_ALL';
export const REQUEST_MENU_PRODUCT ='REQUEST_MENU_PRODUCT';
export const REQUEST_TITLE = 'REQUEST_TITLE';
export const ADD_TOCART = 'ADD_TOCART';
export const REQUEST_LIST_CART ='REQUEST_LIST_CART';
export const DELETE_ITEM_CART ='DELETE_ITEM_CART';